### PR TITLE
Add support for WDK10

### PR DESCRIPTION
**Pull request by wbagdon**
- Add support for WDK10 installs
- Remove unnecessary `*.iml` files
- Bump TC version to 2017.2
- Bump JDK to 1.8

### CODE REVIEW

**Comment by jozefizso** [comment]
Hi, thanks for the contribution.

Can you split the changes to individual logical parts?

I expect the WDK10 detection does not require Java 8, etc.

**Comment by wbagdon** [comment]
I'm using the diamond operator which was added in JDK7.
So it's at least a requirement of the way I wrote the WDK10 detection.
I can split out the commit so that I'm updating the JDK and then add support for WDK10 if you want.

**Comment by jozefizso** [comment]
The <> is used just on two places. It can use the normal version.

**Comment by wbagdon** [comment]
@jozefizso I've backed out changed to the JDK, but it appears Travis CI build is not working now due to a JDK install issue.

**Comment by jozefizso** [comment]
I cherrypicked changes with the Windows 10 SDK detector and put it on master branch.

**Comment by jozefizso** [comment]
Implemented in [v2.4.0](https://github.com/jozefizso/teamcity-microsoftsdks/releases/tag/v2.4.0)

**Pull request closed without merging**
